#if !canImport(ObjectiveC)
import XCTest

extension CHIP8MachineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CHIP8MachineTests = [
        ("testDelayTimer", testDelayTimer),
        ("testIntructionRegister", testIntructionRegister),
        ("testMemSize", testMemSize),
        ("testProgramCounter", testProgramCounter),
        ("testRegisterSize", testRegisterSize),
        ("testSoundTimer", testSoundTimer),
        ("testStackPointer", testStackPointer),
        ("testStackSize", testStackSize),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CHIP8MachineTests.__allTests__CHIP8MachineTests),
    ]
}
#endif
