name: CI

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Ubuntu lidsdl2-dev
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get -y install libsdl2-dev
    
    - name: Install Mac lidsdl2-dev
      if: matrix.os == 'macOS-latest'
      run: |
        brew update
        brew install sdl2

    - name: Run test (in Release, with optimization level)
      run: |
        swift test -Xswiftc -O

    - name: Compile project (in Release)
      run: |
        swift build -c release
    
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Prepare upload
      run: |
        mv .build/release/CHIP8App CHIP8App
        chmod 700 CHIP8App
    
    - uses: actions/upload-artifact@v2
      with:
        name: CHIP8App--${{ steps.slug.outputs.sha8 }}-${{matrix.os}}
        path: CHIP8App

    # - name: Create tag name
    #   if: startsWith(github.ref, 'refs/tags/') != true
    #   run: |
    #     export TAGNAME="snapshot_$(date +'%Y_%m_%d_%H%M%S')"
    #     echo "::set-env name=NEW_TAGNAME::$TAGNAME"
    
    # - name: Use tag name
    #   if: startsWith(github.ref, 'refs/tags/')
    #   run: |
    #     export TAGNAME="$(echo ${GITHUB_REF##*/})"
    #     echo "::set-env name=NEW_TAGNAME::$TAGNAME"
    
    # - name: Release
    #   if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: lib_s.tar.gz
    #     tag_name: ${{ env.NEW_TAGNAME }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
