name: CI-compile

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        dnf -y update
        dnf -y install swift-lang SDL2-devel git
        
    - name: Run test (in Debug, without optimization level)
      run: |
        swift test
    
    - name: Run test (in Release, with optimization level)
      run: |
        swift test -Xswiftc -O

    - name: Compile project (in Release)
      run: |
        swift build -c release
    
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Prepare upload
      run: |
        mv .build/release/CHIP8App CHIP8App
    
    - uses: actions/upload-artifact@v2
      with:
        name: CHIP8App--${{ steps.slug.outputs.sha8 }}-fedora-latest
        path: CHIP8App
