name: CI-compile

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        dnf -y update
        dnf -y install swift-lang SDL2
